CREATE TABLE USUARIO(
    ID_USUARIO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(20) NOT NULL,
    TRABAJO INTEGER NOT NULL,
    TELEFONO CHAR(12),
    EMAIL VARCHAR(30),
    FECHANACIMIENTO DATE,
    IMAGEN VARCHAR(20),
    ESTADOCIVIL VARCHAR(20),
    GRUPOSANGUINEO CHAR(2),
    CONSTRAINT ID_USUARIO_PK PRIMARY KEY (ID_USUARIO),
    CONSTRAINT USUARIO_TRABAJO_FK FOREIGN KEY (TRABAJO) REFERENCES TRABAJO(ID_TRABAJO)
);

CREATE TABLE TRABAJO(
    ID_TRABAJO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(20) NOT NULL,
    EMPRESA VARCHAR(20),
    HORAS_SEMANALES SMALLINT NOT NULL,
    SALARIO DECIMAL(6,2),
    FECHA_ADMISION DATE,
    CONSTRAINT ID_TRABAJO_PK PRIMARY KEY (ID_TRABAJO)
);

